language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install -y libxml2-dev
  - pip install coverage
script:
  - pytest
  - convert pic.jpg pic.png

after_success:
  - coverage report
